### ISSUE TITLE
After adding in config/plugins the Plugin is still not shown in the UI

### ISSUE THREAD

**Issue by AllPlayer** [MaksZhukov/strapi-plugin-generate-data#27]
The plugins file was missing so I created it with below content

`export default ({ env }) => ({
  "generate-data": {
    enabled: true,
  },
});
`

The project is in TS
The plugin was still not visible after restarting.

**Comment by MaksZhukov** [comment]
@AllPlayer Hey! It works from my side for strapi 4.4.3 with ts
![image](https://user-images.githubusercontent.com/23615115/196188117-f920fd99-08cf-4198-992e-4c5577fd3d02.png)
![image](https://user-images.githubusercontent.com/23615115/196188150-a03999d5-4724-4e2d-8056-69a3a9437b94.png)
![image](https://user-images.githubusercontent.com/23615115/196188195-0c2c1177-3f0c-4550-8d0e-0012696d1181.png)

**Comment by MaksZhukov** [comment]
@AllPlayer Any updates?

**Comment by AllPlayer** [comment]
I upgraded strapi to your version from 4.2.0 and it works now thank you.

**Comment by neural-loop** [comment]
Might reopen this. I recently found strapi, and through the interface I installed the package

![image](https://user-images.githubusercontent.com/654993/198985367-bb14f7fb-7f09-4fbd-9e13-203c88099bd0.png)

Created the plugins.js (didn't exist already)
![image](https://user-images.githubusercontent.com/654993/198985498-f2da5d2d-5705-4e07-ad06-7e72f8eaefed.png)

And I haven't been able to figure out how to enable it. Am I missing something?

**Comment by neural-loop** [comment]
Update, I checked on the production install and I see it there. Hmm

**Comment by MaksZhukov** [comment]
@neural-loop Hey, thanks. What are differences for production install and just install?

**Comment by neural-loop** [comment]
What I meant is I have my local version which I run locally with
`strapi develop` (Generate data doesn't appear)

When I push to heroku in 'production' mode (`strapi start` , I think), it does appear. And production doesn't have the plugins.js file yet

**Comment by neural-loop** [comment]
Also, it's not just your plugin that I see in production environment but not in my develop environment. I see also the 'Documentation' and 'Custom-links' plugins that I had installed but hadn't seen the menu items for. 
It's a bit confusing because it's not completely consistent. For example I had also installed the Passwordless plugin which did appear in my settings menu in the develop environment without modifying anything.
I think that there is a 'plugins' tab that shows that these are installed might be a bit confusing if it is also necessary to enable it within the plugins.js.  When I saw Generate Data in the plugins list, I assumed that meant I should also see it in the menu.

**Comment by MaksZhukov** [comment]
Ok, I will check

**Comment by MaksZhukov** [comment]
@neural-loop Which version of strapi are you using?

**Comment by neural-loop** [comment]
I'm on 4.4.5. Node version v18.12.0

It's possible that I've missed some step also, I've only been using strapi for a few days. Didn't notice the config/plugins.js until I was investigating this. It seems odd that they all appear in the production run, and not the develop run when there isn't a plugins.js.  Perhaps the develop is seen more as a mode setting up content types not a sandbox.

**Comment by neural-loop** [comment]
Hmm. I tried `strapi start` locally and I don't see the plugins. Maybe I should try clearing out my node_modules. I might have tried installing the plugin while strapi was running.

**Comment by neural-loop** [comment]
Hi, I confirm that solved it. I think I had corrupted my local install by trying to run one of the install commands from the 'marketplace' while strapi was running and didn't realize it would partially install / break. I didn't think too much of the warnings since it still showed up in my installed plugins list. 

Can close this again. Was user error
