### ISSUE TITLE
Not installing on Node v18.0.0

### ISSUE THREAD

**Issue by akinabudu** [MaksZhukov/strapi-plugin-generate-data#29]
Hello,
error strapi-plugin-generate-data@1.0.19: The engine "node" is incompatible with this module. Expected version ">=12.x.x <=16.x.x". Got "18.0.0"
error Found incompatible module.

**Comment by MaksZhukov** [comment]
@akinabudu Hey! Thanks, which module is incompatible? I will check

**Comment by MaksZhukov** [comment]
@akinabudu Try to use another version of node maybe, because it works from my side
![image](https://user-images.githubusercontent.com/23615115/202413908-3af9be19-ac05-442e-9d82-0000a204ea7b.png)
![image](https://user-images.githubusercontent.com/23615115/202413951-53274437-2edc-46a3-aabc-3f0bc143feb4.png)

**Comment by MaksZhukov** [comment]
@akinabudu Hey! Any updates?
